language: go

go:
 - 1.7

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_install:
 - go get github.com/mitchellh/gox
 - gox -build-toolchain
 - go get github.com/tcnksm/ghr

script:
 - go test -v ./...
 - go vet

after_success:
 - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
 - ghr --username chuyskywalker --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
