language: go

go:
 - 1.7

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

script:
  - go test -v ./...
  - go vet

deploy:
  # Release a tagged version
  - provider: script
    script: scripts/tag-deploy.sh
    on:
      tags: true
  # Update the "pre-release" version
  - provider: script
    script: scripts/pre-release.sh
    on:
      branch: master
