language: go

go:
 - 1.7

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

script:
  - go test -v ./...
  - go vet

after_success:
  - go get github.com/tcnksm/ghr
  - go get github.com/mitchellh/gox
  - gox -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}"
  - cd dist; for i in *; do zip -v $i.zip $i; rm $i; done

deploy:
  - provider: script
    script: ghr --username chuyskywalker --token $GITHUB_TOKEN --replace $TRAVIS_TAG .
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ghr --username chuyskywalker --token $GITHUB_TOKEN --recreate pre-release .
    skip_cleanup: true
    on:
      branch: master
